### ISSUE TITLE
Discuss how to use gifs in the tool

### ISSUE THREAD

**Issue by rahuldkjain** [rahuldkjain/github-profile-readme-generator#10]
Things to brainstorm
- UI/UX
- gif resources

**Comment by abhijit-hota** [comment]
I have a suggestion for UI/UX. I considered opening a new issue as this issue is just for discussion.
Here it is:

**The problem:** As the web app grows and becomes larger, the number of **skills** and **online developer platforms/social media** grows with it. This make the page longer.  

**The solution:** A dropdown menu with a longer list of skills. Users can just search for the relevant skills and put them up.
We may implement something like the picture below for websites. (source: Heroku settings).

![image](https://user-images.githubusercontent.com/8116174/88283706-949df100-cd09-11ea-9e79-eff40a6d6bf5.png)
 Replace the `KEY` input with `Website` and `VALUE` with `Username` and you get the idea what I'm talking about. The `Website` input element will be a dropdown list so that we don't have to validate a website again. Same can be done for skills but with only one dropdown.

This version is better because:
- A user won't have to search for his skills among the vast scattered list. (I know it's supposed to be alphabetical but again it's still searching). They don't have to find Javascript among a plethora of all the other languages they don't know. 
- Will look better.

Just a suggestion =)

**Comment by rahuldkjain** [comment]
Making the list alphabetically sorted will be nice point to start with.

**Comment by abhijit-hota** [comment]
> Making the list alphabetically sorted will be nice point to start with. 

Ok.

**Comment by ankurchaudhary627** [comment]
@rahuldkjain @abhijit-hota  We can probably use `elastic search` for searching the skills as the user types in the input box. We can put minimum character limit to be 3 or 4 after which we filter and show the filtered options in the dropdown as the user types making the search more user friendly.

**Comment by abhijit-hota** [comment]
> @rahuldkjain @abhijit-hota  We can probably use `elastic search` for searching the skills as the user types in the input box. We can put minimum character limit to be 3 or 4 after which we filter and show the filtered options in the dropdown as the user types making the search more user friendly.

Yes! This seems nice and minimal. 👍

**Comment by rahuldkjain** [comment]
@abhijit-hota @ankurchaudhary627 I think basic JS Filter will do the work easily. Just curious to know why to use Elastic Search here with such less data.

**Comment by ankurchaudhary627** [comment]
@rahuldkjain I suggest using elastic search because the skills list can be very long where we can efficiently use this. If we use JS filter, the user will have to type the skill name completely and then only we will filter out the skills based on inputs. But on the same hand if we use elastic search, it will be dynamic filtering as the user types the skills. It leads to optimized filtering as compared to the JS filter.

**Comment by rahuldkjain** [comment]
@ankurchaudhary627 yeah sounds great.
