### ISSUE TITLE
Profile views tag increments everytime

### ISSUE THREAD

**Issue by Saumya-Mishra9129** [rahuldkjain/github-profile-readme-generator#2]
This can be seen even on opening or reloading my own profile , it needs improvement.

**Comment by rahuldkjain** [comment]
Thanks for pointing it out. I am using [github-profile-views-counter](https://github.com/antonkomarev/github-profile-views-counter) service for the same. The reason for choosing this service is the premium domain hosting(not on free glitch service) so that it never breaks down with a bad message like `too many requests`. 
I am opening an issue on the service repository.

Thanks again.

**Comment by rahuldkjain** [comment]
The develop of [github-profile-views-counter](https://github.com/antonkomarev/github-profile-views-counter) says that the service is meant for `view count` not for `unique view count` and GitHub proxies images thru the `camo.githubusercontent.com` domain, so we don't have any way to check if it's a new user or somebody who already seen your profile today.

So I am closing this issue as of now!

Original thread
https://github.com/antonkomarev/github-profile-views-counter/issues/5

**Comment by Saumya-Mishra9129** [comment]
@rahuldkjain Can we not use any different service , and can handle bad message by some way.? I am looking forward for it.

**Comment by rahuldkjain** [comment]
@Saumya-Mishra9129 I am not aware of any other service that solves this issue. Will update the service, if I find a better alternative.
