### ISSUE TITLE
Some icons are not showing in the programming and connect with me section.

### ISSUE THREAD

**Issue by Ashish-9455187250** [rahuldkjain/github-profile-readme-generator#757]
**When selecting the icons some icons are not loading.**
**I have attached a screenshot**

![Screenshot (3)](https://github.com/rahuldkjain/github-profile-readme-generator/assets/94695243/9f097e8c-b3bf-492c-acdc-2f0eb5b41b61)

**Comment by sarafurd** [comment]
Please assign this to me

**Comment by deveshkoli** [comment]
Hello, I see that all the icons are showing up on my side of the browser. Can you please elaborate how you got this bug. If you can please share how you can recreate the problem. 

Thank you

**Comment by Ashish-9455187250** [comment]
When I was creating my readme profile by using this readme generator, I faced this issue where some icons in the programming section and connect with me section are not showing as well as in my readme profile repository also. So then I faced this issue

**Comment by deveshkoli** [comment]
> When I was creating my readme profile by using this readme generator, I faced this issue where some icons in the programming section and connect with me section are not showing as well as in my readme profile repository also. So then I faced this issue

Okay, I see that you have changed the Logo/icons as per your imagination. That's cool. I guess. This issue should be **closed** as other people were also having the same problem but one of the comments suggested to have a high speed internet. 

https://github.com/rahuldkjain/github-profile-readme-generator/issues/748#issuecomment-1689491999

Maybe having that would solve the issue. I also faced this issue on my first boot Maybe the Server side was slow. Because when I faced this issue I also had refreshed the page and all the icons were visible. 

Maybe you can checkout my profile. It shows all of the icons now. Maybe this ain't a bug. More like internet speed issues.

**Comment by Ashish-9455187250** [comment]
I don't think so it can be a high internet speed issue because I have a 5g connection which gives me a speed of around 40 to 50 Mb/s and its enough for loading a huge application also, Maybe this is some server side issue. And I saw your Id it is very nice but again some icons are not showing in your profile. I am attaching a screenshot you can see as well, but no problem as I have created my readme profile by myself so this issue can be **closed**


![Screenshot (4)](https://github.com/rahuldkjain/github-profile-readme-generator/assets/94695243/7694c978-9ecb-4de0-897c-a70d578f1384)

**Comment by bkmahapatra** [comment]
Please assign this issue to me.

**Comment by Ashish-9455187250** [comment]
.take

**Comment by Ashish-9455187250** [comment]
Ok I'll assign it to you

**Comment by bilalshaikh292** [comment]
Heyy this Issue is not  yet fixed ? can I contribute ?
